### ISSUE TITLE
Lab Report 1 Feedback

### ISSUE THREAD

**Issue by AmanKAggarwal** [lineup30min/cse15l-lab-reports#1]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
- [x] All relevant code examples written with backticks (```)
- [x] All screenshots correspond to the described steps
- [x] All titles of sections are formatted as headers or similar
- [x] Lab report is on its own page, not the index page
- [x] Last example shows how to run remotely saving time
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:
Your submission for the **Report URL** was [this](https://github.com/lineup30min/cse15l-lab-reports/blob/main/lab-report-1-week-2.md) which does not take us to your report website but to the location in github where the file is present. 
Also, since you have a `lab-report-1-week-2.html` file inside the repository, when I try to access the actual report URL which is [this](https://lineup30min.github.io/cse15l-lab-reports/lab-report-1-week-2.html) it loads up the empty html file. Please remove that html file so that the markdown file can be loaded inside the browser and your report can be graded. 

From looking at the markdown, some issues I noticed was not all your code examples had backticks. For example, in Trying Some Commands. 

I'm unable to give you points for the lab at the moment but please make the necessary changes and submit a regrade request.

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by lineup30min** [comment]
Thank you for the feedback, I will make changes later! But I was wondering do I need to change something other than backticks for my content in the lab report. Since it seemed that I got none checkmarks, I was worried.

**Comment by AmanKAggarwal** [comment]
Unfortunately, I can't grade your website until the regrade request deadline is over but make sure to submit a regrade request with the correct website link. I was unable to check your website which is why you got no checkmarks, so don't worry too much about it because once you get your regrade request in I will compare these rubric items with your submission and will assign grades accordingly. Best tip I can give you is try to grade yourself with these tasks to see where you stand!

**Comment by AmanKAggarwal** [comment]
Good work!!
